### ISSUE TITLE
Verificar el tamaño de la imagen al crear un producto cuando seleccionas UNA sola imagen

### ISSUE THREAD

**Issue by Fedesan14** [7-Seven-Up/megastore-frontend#30]
Cuando se crea o edita un producto, si se selecciona una sola imagen, ésta no se ve bien, tiene demasiado tamaño

**Comment by delgadomatias** [comment]
Acá el equipo debe decidir, tenemos dos escenarios:
1. Si hacemos que la imagen ocupe un tamaño adecuado, ocurre que pueden quedar espacios en blancos.
2. Si lo dejamos como está y seleccionamos pocas imágenes, pueden ocupar un gran tamaño.

Adjunto ejemplo de los escenarios posibles:

![image](https://github.com/user-attachments/assets/f52482fb-71a7-429f-acfa-272026744c42)

![image](https://github.com/user-attachments/assets/c440a92c-213e-4105-ab19-1975e19658da)

**Comment by Fedesan14** [comment]
Prefiero la opcion 1 :)
